- hosts: all
  become: yes
  name: installing packages,building and containerize the application
  tasks:
    - name: updating the machine
      apt:
        upgrade: dist
        update_cache: yes
    - name: Installing and docker
      apt:
        name: docker.io
    - name: Deploy Docker Container
      command: docker run -itd --name finance -p 8081:8081 laxg66/finance-tg:v1
